package com.vikkash.assetmanagementv1.service;

import com.vikkash.assetmanagementv1.dto.TaskRequest;
import com.vikkash.assetmanagementv1.entity.Task;
import com.vikkash.assetmanagementv1.exception.ResourceNotFoundException;
import com.vikkash.assetmanagementv1.repository.TaskRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Haoda Pulse: the task module that drives task-based reminders in the
 * Enterprise Notification Center. Creating, assigning, and completing a
 * task each generate a synchronized in-app + email notification
 * (per the "Immediately after task creation" and "When completed" rules);
 * day-based reminders (7/3/1 days before, due today, overdue) are
 * generated by PulseReminderScheduler.
 */
@Service
public class TaskService {

    private final TaskRepository repository;
    private final NotificationService notificationService;

    public TaskService(TaskRepository repository, NotificationService notificationService) {
        this.repository = repository;
        this.notificationService = notificationService;
    }

    @Transactional(readOnly = true)
    public List<Task> getAll() {
        return repository.findAllByOrderByDueDateAscCreatedAtDesc();
    }

    @Transactional(readOnly = true)
    public Task getById(Long id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found with id: " + id));
    }

    @Transactional
    public Task create(TaskRequest req, String createdBy) {
        Task task = new Task();
        task.setTitle(req.getTitle());
        task.setDescription(req.getDescription());
        task.setCategory(blankToDefault(req.getCategory(), "General"));
        task.setPriority(blankToDefault(req.getPriority(), "Normal"));
        task.setStatus("Pending");
        task.setAssigneeId(req.getAssigneeId());
        task.setAssigneeName(req.getAssigneeName());
        task.setAssigneeEmail(req.getAssigneeEmail());
        task.setDueDate(req.getDueDate());
        task.setRelatedModule(req.getRelatedModule());
        task.setRelatedRecordId(req.getRelatedRecordId());
        task.setCreatedBy(createdBy);
        task = repository.save(task);

        // Rule: generate a notification immediately after task creation.
        NotificationService.Recipients recipients = new NotificationService.Recipients();
        recipients.assigneeEmail = task.getAssigneeEmail();
        String desc = "Due " + (task.getDueDate() != null ? task.getDueDate() : "no due date") +
                (task.getAssigneeName() != null ? " · Assigned to " + task.getAssigneeName() : "");
        notificationService.create(
                task.getAssigneeId() != null ? "TASK_ASSIGNED" : "UPCOMING_TASK",
                "Task", task.getPriority(),
                task.getAssigneeId() != null ? ("Task assigned: " + task.getTitle()) : ("New task: " + task.getTitle()),
                desc, "TASK", String.valueOf(task.getId()), task.getDueDate(), recipients);

        // Rule: high-priority tasks get an immediate dedicated alert too.
        if ("High".equalsIgnoreCase(task.getPriority()) || "Critical".equalsIgnoreCase(task.getPriority())) {
            notificationService.create("HIGH_PRIORITY_TASK", "Task", task.getPriority(),
                    "High priority: " + task.getTitle(), desc, "TASK", String.valueOf(task.getId()), task.getDueDate(), recipients);
        }
        return task;
    }

    @Transactional
    public Task update(Long id, TaskRequest req) {
        Task task = getById(id);
        task.setTitle(req.getTitle());
        task.setDescription(req.getDescription());
        if (req.getCategory() != null) task.setCategory(req.getCategory());
        if (req.getPriority() != null) task.setPriority(req.getPriority());
        task.setAssigneeId(req.getAssigneeId());
        task.setAssigneeName(req.getAssigneeName());
        task.setAssigneeEmail(req.getAssigneeEmail());
        task.setDueDate(req.getDueDate());
        task.setRelatedModule(req.getRelatedModule());
        task.setRelatedRecordId(req.getRelatedRecordId());
        return repository.save(task);
    }

    @Transactional
    public Task updateStatus(Long id, String status) {
        Task task = getById(id);
        task.setStatus(status);
        if ("Completed".equalsIgnoreCase(status)) {
            task.setCompletedAt(LocalDateTime.now());
            NotificationService.Recipients recipients = new NotificationService.Recipients();
            recipients.assigneeEmail = task.getAssigneeEmail();
            notificationService.create("TASK_COMPLETED", "Task", "Low",
                    "Completed: " + task.getTitle(),
                    "Marked complete" + (task.getAssigneeName() != null ? " by " + task.getAssigneeName() : "") + ".",
                    "TASK", String.valueOf(task.getId()), task.getDueDate(), recipients);
        }
        return repository.save(task);
    }

    @Transactional
    public void delete(Long id) {
        Task task = getById(id);
        repository.delete(task);
    }

    private String blankToDefault(String v, String def) {
        return (v == null || v.isBlank()) ? def : v;
    }
}
